#x,y,z coordinate of closest obstacle point of each frame 2 - EndEffector
#frame 2
# distance between obstacle and closest point on obstacle
float64 frame2x 
float64 frame2y
float64 frame2z
float64[42] jacobian2
# coordinate of closest point 
float64 point2x
float64 point2y
float64 point2z


#frame 3
float64 frame3x
float64 frame3y
float64 frame3z

float64 point3x
float64 point3y
float64 point3z
float64[42] jacobian3
#frame 4
float64 frame4x
float64 frame4y
float64 frame4z

float64 point4x
float64 point4y
float64 point4z
float64[42] jacobian4
#frame 5
float64 frame5x
float64 frame5y
float64 frame5z

float64 point5x
float64 point5y
float64 point5z
float64[42] jacobian5
#frame 6
float64 frame6x
float64 frame6y
float64 frame6z

float64 point6x
float64 point6y
float64 point6z
float64[42] jacobian6
#frame 7
float64 frame7x
float64 frame7y
float64 frame7z

float64 point7x
float64 point7y
float64 point7z
float64[42] jacobian7
#frame EndEffector
float64 frameeex
float64 frameeey
float64 frameeez

float64 pointeex
float64 pointeey
float64 pointeez
float64[42] jacobianee