
#frame 2
# distance between obstacle and closest point on obstacle
float64[] frame2x 
float64[] frame2y
float64[] frame2z
float64[] jacobian2

#frame 3
float64[] frame3x
float64[] frame3y
float64[] frame3z
float64[] jacobian3

#frame 4
float64[] frame4x
float64[] frame4y
float64[] frame4z
float64[] jacobian4


#frame 5
float64[] frame5x
float64[] frame5y
float64[] frame5z
float64[] jacobian5

#frame 6
float64[] frame6x
float64[] frame6y
float64[] frame6z
float64[] jacobian6

#frame 7
float64[] frame7x
float64[] frame7y
float64[] frame7z
float64[] jacobian7

#frame hand
float64[] framehandx
float64[] framehandy
float64[] framehandz
float64[] jacobianhand

#frame EndEffector
float64[] frameeex
float64[] frameeey
float64[] frameeez
float64[] jacobianee